"""
Conversation and knowledge sharing tools
Support general Q&A, explanations, and casual conversation
"""

import logging
from typing import Dict, Any, List, Optional
from ..base import Tool, ToolParameter

logger = logging.getLogger(__name__)


class AnswerQuestionTool(Tool):
    """Answer general questions and provide information"""
    
    @property
    def name(self) -> str:
        return "answer_question"
    
    @property
    def description(self) -> str:
        return (
            "Answer general questions, provide explanations, share knowledge, and engage in conversation. "
            "Use this for questions about concepts, facts, how things work, definitions, or when the user "
            "wants to have a general conversation. This is JARVIS's main conversational tool."
        )
    
    @property
    def parameters(self) -> List[ToolParameter]:
        return [
            ToolParameter(
                name="question",
                type="string",
                description="The user's question or statement to respond to",
                required=True
            ),
            ToolParameter(
                name="topic",
                type="string",
                description="Main topic category (technology, science, general, casual, etc.)",
                required=False,
                default="general"
            ),
            ToolParameter(
                name="response_style",
                type="string",
                description="How to respond: 'concise' (brief), 'detailed' (thorough), 'casual' (friendly chat)",
                required=False,
                default="concise"
            )
        ]
    
    def execute(
        self,
        question: str,
        topic: str = "general",
        response_style: str = "concise",
        **kwargs
    ) -> Dict[str, Any]:
        """
        This tool signals that the user wants a conversational response.
        The actual response will be generated by the LLM, but this tool
        provides structure and metadata for the conversation.
        """
        try:
            logger.info(f"Answering question: {question[:50]}...")
            
            # Build response metadata
            return {
                "success": True,
                "question": question,
                "topic": topic,
                "response_style": response_style,
                "action": "answer_question",
                "requires_llm_response": True,  # Signal to generate LLM response
                "message": "Processing your question..."
            }
            
        except Exception as e:
            logger.error(f"Error in answer_question: {e}")
            return {
                "success": False,
                "error": str(e)
            }


class ExplainConceptTool(Tool):
    """Explain technical concepts, terms, or how things work"""
    
    @property
    def name(self) -> str:
        return "explain_concept"
    
    @property
    def description(self) -> str:
        return (
            "Explain technical concepts, definitions, how things work, or provide tutorials. "
            "Use this when the user asks 'explain X', 'what is X', 'how does X work', or "
            "wants to learn about something."
        )
    
    @property
    def parameters(self) -> List[ToolParameter]:
        return [
            ToolParameter(
                name="concept",
                type="string",
                description="The concept, term, or topic to explain",
                required=True
            ),
            ToolParameter(
                name="complexity",
                type="string",
                description="Explanation level: 'simple' (beginner), 'intermediate', 'advanced'",
                required=False,
                default="intermediate"
            )
        ]
    
    def execute(
        self,
        concept: str,
        complexity: str = "intermediate",
        **kwargs
    ) -> Dict[str, Any]:
        """Signal that user wants an explanation"""
        try:
            logger.info(f"Explaining concept: {concept}")
            
            return {
                "success": True,
                "concept": concept,
                "complexity": complexity,
                "action": "explain_concept",
                "requires_llm_response": True,
                "message": f"Explaining {concept}..."
            }
            
        except Exception as e:
            logger.error(f"Error in explain_concept: {e}")
            return {
                "success": False,
                "error": str(e)
            }


class HaveConversationTool(Tool):
    """Engage in casual conversation, small talk, or general chat"""
    
    @property
    def name(self) -> str:
        return "have_conversation"
    
    @property
    def description(self) -> str:
        return (
            "Engage in general conversation, small talk, casual chat, or respond to greetings. "
            "Use this when the user is having a friendly conversation, making casual remarks, "
            "or when there's no specific task to perform."
        )
    
    @property
    def parameters(self) -> List[ToolParameter]:
        return [
            ToolParameter(
                name="message",
                type="string",
                description="The user's conversational message",
                required=True
            ),
            ToolParameter(
                name="conversation_type",
                type="string",
                description="Type: 'greeting', 'small_talk', 'opinion', 'chat', 'joke'",
                required=False,
                default="chat"
            )
        ]
    
    def execute(
        self,
        message: str,
        conversation_type: str = "chat",
        **kwargs
    ) -> Dict[str, Any]:
        """Signal conversational interaction"""
        try:
            logger.info(f"Conversation: {conversation_type}")
            
            # Handle simple greetings directly
            greetings_responses = {
                "hello": "Hello! How can I assist you?",
                "hi": "Hi there! What can I do for you?",
                "hey": "Hey! How can I help?",
                "good morning": "Good morning! Ready to assist you.",
                "good afternoon": "Good afternoon! How can I help?",
                "good evening": "Good evening! What can I do for you?",
                "how are you": "I'm functioning perfectly, thank you! How can I assist you today?",
                "what's up": "Ready to help! What do you need?",
            }
            
            message_lower = message.lower().strip()
            
            # Check for simple greetings
            for greeting, response in greetings_responses.items():
                if greeting in message_lower:
                    return {
                        "success": True,
                        "message": message,
                        "conversation_type": "greeting",
                        "action": "have_conversation",
                        "direct_response": response,
                        "requires_llm_response": False
                    }
            
            # For other conversations, use LLM
            return {
                "success": True,
                "message": message,
                "conversation_type": conversation_type,
                "action": "have_conversation",
                "requires_llm_response": True
            }
            
        except Exception as e:
            logger.error(f"Error in have_conversation: {e}")
            return {
                "success": False,
                "error": str(e)
            }
